#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    dpkg-trigger update-workbench
}

case "$1" in
    purge)
        remove_action

        if [ -d "/opt/omv-hddfanctrl" ]; then
            rm -rf /opt/omv-hddfanctrl
        fi

        if [ -f /etc/omv-hddfanctrl/fanctrl.conf ]; then
          rm /etc/omv-hddfanctrl/fanctrl.conf
        fi

        omv_config_delete "/config/system/hddfanctrl"
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
